server:
    port: 8082

spring:
    application:
        name: zaplink-processor-service
    # Enable Virtual Threads (Java 21+)
    threads:
        virtual:
            enabled: true
    # Kafka config
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-offset-reset: latest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        properties:
            "spring.deserializer.value.delegate.class": org.springframework.kafka.support.serializer.JacksonJsonDeserializer
            "spring.json.trusted.packages": "*"
            "spring.json.use.type.headers": true
            "spring.json.type.mapping": urlClickEvent:io.zaplink.processor.dto.event.UrlClickEvent,qrScanEvent:io.zaplink.processor.dto.event.QrScanEvent
    # Redis config
    data:
        redis:
            host: localhost
            port: 6379
    # DataSource config
    datasource:
        url: jdbc:postgresql://localhost:5432/zaplink_core
        username: postgres
        password: 12345
    # JPA config
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

# Batch Processing Configuration
zaplink:
    batch:
        flush-interval: 15000  # Flush every 5 seconds (5000ms)