-- Create tables for RBAC and Team Management in core schema

-- Organizations table
CREATE TABLE IF NOT EXISTS core.organizations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    owner_id BIGINT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);

-- Teams table
CREATE TABLE IF NOT EXISTS core.teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    organization_id BIGINT NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (organization_id) REFERENCES core.organizations(id)
);

-- Team members table
CREATE TABLE IF NOT EXISTS core.team_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('ADMIN', 'EDITOR', 'APPROVER', 'VIEWER', 'INFLUENCER')),
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'PENDING')),
    invited_by BIGINT NOT NULL,
    invited_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    joined_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (team_id) REFERENCES core.teams(id),
    FOREIGN KEY (user_id) REFERENCES auth.users(id),
    FOREIGN KEY (invited_by) REFERENCES auth.users(id),
    UNIQUE(team_id, user_id)
);

-- Campaigns table
CREATE TABLE IF NOT EXISTS core.campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    campaign_id VARCHAR(255) UNIQUE, 
    description TEXT,
    campaign_type VARCHAR(20) NOT NULL DEFAULT 'GENERAL' CHECK (campaign_type IN ('GENERAL', 'QR_CODE', 'SOCIAL_MEDIA', 'EMAIL_MARKETING', 'INFLUENCER', 'VIDEO', 'AUDIO', 'TEXT', 'IMAGE', 'OTHER')),
    user_email VARCHAR(255),
    organization_id BIGINT NOT NULL,
    status VARCHAR(20) DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'INACTIVE', 'DELETED', 'SCHEDULED')),
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (organization_id) REFERENCES core.organizations(id),
    FOREIGN KEY (created_by) REFERENCES auth.users(id)
);

-- Campaign assignments (for influencers)
CREATE TABLE IF NOT EXISTS core.campaign_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL,
    team_member_id BIGINT NOT NULL,
    status VARCHAR(20) DEFAULT 'ASSIGNED' CHECK (status IN ('ASSIGNED', 'IN_PROGRESS', 'COMPLETED')),
    assigned_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE,
    FOREIGN KEY (campaign_id) REFERENCES core.campaigns(id),
    FOREIGN KEY (team_member_id) REFERENCES core.team_members(id),
    UNIQUE(campaign_id, team_member_id)
);

-- Posts table
CREATE TABLE IF NOT EXISTS core.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    campaign_id BIGINT,
    author_id BIGINT NOT NULL,
    status VARCHAR(20) DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'PUBLISHED')),
    submitted_at TIMESTAMP WITH TIME ZONE,
    reviewed_by BIGINT,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    review_comments TEXT,
    published_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (campaign_id) REFERENCES core.campaigns(id),
    FOREIGN KEY (author_id) REFERENCES auth.users(id),
    FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);

-- Insert default organization and team for demo
-- First, let's handle the foreign key constraint by either using an existing user or creating a placeholder user
DO $$
DECLARE
    existing_user_id BIGINT;
    org_id BIGINT;
BEGIN
    -- Try to find any existing user in auth.users
    SELECT id INTO existing_user_id FROM auth.users LIMIT 1;
    
    IF existing_user_id IS NOT NULL THEN
        -- Insert organization with existing user as owner
        INSERT INTO core.organizations (name, description, owner_id) 
        VALUES ('Zaplink Demo Organization', 'Default organization for demonstration', existing_user_id)
        ON CONFLICT (id) DO NOTHING;
    ELSE
        -- If no users exist, create a placeholder user first
        INSERT INTO auth.users (id, email, username, password_hash, created_at, updated_at)
        VALUES (1, 'admin@zaplink.com', 'admin', '$2a$10$placeholder.hash.here', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        ON CONFLICT (id) DO NOTHING;
        
        -- Now insert organization with the placeholder user
        INSERT INTO core.organizations (name, description, owner_id) 
        VALUES ('Zaplink Demo Organization', 'Default organization for demonstration', 1)
        ON CONFLICT (id) DO NOTHING;
    END IF;
END $$;

-- Get the organization ID and insert the default team
INSERT INTO core.teams (name, description, organization_id) 
SELECT 'Default Team', 'Default team for demonstration', id 
FROM core.organizations 
WHERE name = 'Zaplink Demo Organization'
LIMIT 1
ON CONFLICT DO NOTHING;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_team_members_team_id ON core.team_members(team_id);
CREATE INDEX IF NOT EXISTS idx_team_members_user_id ON core.team_members(user_id);
CREATE INDEX IF NOT EXISTS idx_team_members_role ON core.team_members(role);
CREATE INDEX IF NOT EXISTS idx_campaigns_organization_id ON core.campaigns(organization_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON core.campaigns(status);
CREATE INDEX IF NOT EXISTS idx_posts_author_id ON core.posts(author_id);
CREATE INDEX IF NOT EXISTS idx_posts_status ON core.posts(status);
CREATE INDEX IF NOT EXISTS idx_posts_campaign_id ON core.posts(campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_assignments_campaign_id ON core.campaign_assignments(campaign_id);
CREATE INDEX IF NOT EXISTS idx_campaign_assignments_team_member_id ON core.campaign_assignments(team_member_id);
